### ISSUE TITLE
Error in running Attack.py

### ISSUE THREAD

**Issue by houssem-bouallegui** [Eaphan/Robust3DOD#2]
I am trying to run your code and after following all the guides i reached a point where i am getting an error in your attack.py script
-------------------------------------------------
Traceback (most recent call last):
  File "/home/houssem/Robust3DOD/tools/attack.py", line 740, in <module>
    main()
  File "/home/houssem/Robust3DOD/tools/attack.py", line 733, in main
    eval_one_epoch(
  File "/home/houssem/Robust3DOD/tools/attack.py", line 564, in eval_one_epoch
    annos = dataset.generate_prediction_dicts(
TypeError: generate_prediction_dicts() got an unexpected keyword argument 'flip'
-------------------------------------------------
dataset : kitti
model : pv-rcnn
optimisation : 4
epoch : 1
versions : 
os : using Windows Subsystem for Linux on windows 11
python 3.9
cuda 11.3 WSL version for driver 555+ 
pytorch = 1.10 + cu113

train command : python train.py --cfg_file cfgs/kitti_models/pv_rcnn.yaml --batch_size 4 --epochs 1
attack command : python attack.py --cfg_file tools/cfgs/kitti_models/pvc_rcnn.yaml --ckpt /home/houssem/Robust3DOD/output/kitti_models/pv_rcnn/default/ckpt/checkpoint_epoch_1.pth

**Comment by Eaphan** [comment]
Sorry for the bug. I have fixed this issue in the latest commit.
