### ISSUE TITLE
about running

### ISSUE THREAD

**Issue by leader-of-my-bed** [Eaphan/Robust3DOD#6]
Thank you for your work,sir.
After confirming that the dataset and .pth file , I cannot run attack.py directly using the environment code you provided. However, I can run attack.py on my own configured OpenPCDet after properly setting up the relevant files. I noticed that some files related to PCDet have slight differences compared to those in your code, which might be due to using different versions of PCDet (I'm not sure). Could you confirm whether there is any difference between the two? Is your work mainly focused on the three  .py files?

**Comment by Eaphan** [comment]
My code is based on specific version of pcdet, and we do not test the code on other versions.

**Comment by Eaphan** [comment]
What's the error log information when you run the attack.py directly?

**Comment by leader-of-my-bed** [comment]
tks for reply,i can run attack.py successfully,i just want to make sure if pcdet's version affect the final result.Is there any changed in your pcdet like eval.py？I can get similar result to your paper right now



---Original---
From: "Yifan ***@***.***&gt;
Date: Sat, Dec 7, 2024 10:40 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [Eaphan/Robust3DOD] about running (Issue #6)




 
What's the error log information when you run the attack.py directly?

**Comment by leader-of-my-bed** [comment]
could you please help me ?

when i run

" python attack.py --cfg_file cfgs/kitti_models/pointrcnn.yaml --ckpt pointrcnn.pth --eps 0.11"

i got

Traceback (most recent call last):
  File "/usr/bin/OpenPCDet/tools/attack.py", line 740, in <module>
    main()
  File "/usr/bin/OpenPCDet/tools/attack.py", line 733, in main
    eval_one_epoch(
  File "/usr/bin/OpenPCDet/tools/attack.py", line 145, in eval_one_epoch
    max_num_points_per_voxel = [x['MAX_POINTS_PER_VOXEL'] for x in cfg.DATA_CONFIG.DATA_PROCESSOR if x['NAME']=='transform_points_to_voxels'][0]
IndexError: list index out of range

and i want to know which models are you training yourself,like Part-Aˆ2 、Voxel-RCNN ？
